name: Publish package to Maven Repository
on:
  release:
    types: [created]
jobs:
  publish-maven:
    name: Release build and publish to Maven Repository
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Release build
        run: ./gradlew build
      - name: Publish to MavenCentral
        run: ./gradlew publishAllPublicationToSonatypeRepository --max-workers 1 closeAndReleaseSonatypeStagingRepository
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          SIGNING_SIGNING_KEY: ${{ secrets.SIGNING_SIGNING_KEY }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
  publish-cocoapods:
    name: Release build and publish to Cocoapods
    runs-on: macos-latest
    env:
      VOIZE_COCOAPODS_SPECS_REPO_NAME: ${{ secrets.VOIZE_COCOAPODS_SPECS_REPO_NAME }}
      VOIZE_COCOAPODS_SPECS_REPO_URL: ${{ secrets.VOIZE_COCOAPODS_SPECS_REPO_URL }}
    steps:
      - uses: actions/checkout@v3
      - run: |
          echo "#!/bin/bash" > .git-credentials
          echo "echo username=$VOIZE_COCOAPODS_SPECS_REPO_DEPLOY_KEY_USERNAME" >> .git-credentials
          echo "echo password=$VOIZE_COCOAPODS_SPECS_REPO_DEPLOY_KEY_PASSWORD" >> .git-credentials
        env:
          VOIZE_COCOAPODS_SPECS_REPO_DEPLOY_KEY_USERNAME: ${{ secrets.VOIZE_COCOAPODS_SPECS_REPO_DEPLOY_KEY_USERNAME }}
          VOIZE_COCOAPODS_SPECS_REPO_DEPLOY_KEY_PASSWORD: ${{ secrets.VOIZE_COCOAPODS_SPECS_REPO_DEPLOY_KEY_PASSWORD }}
      - run: git config --global credential.helper "/bin/bash $(pwd)/.git-credentials"
      - run: pod repo add $VOIZE_COCOAPODS_SPECS_REPO_NAME $VOIZE_COCOAPODS_SPECS_REPO_URL
      - run: pod repo push $VOIZE_COCOAPODS_SPECS_REPO_NAME PLMLibTorchWrapper.podspec --use-libraries --allow-warnings
