name: Build and lint project
on: [push, pull_request]
jobs:
  lint-release-podspec:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Lint release podspec
        run: pod spec lint LibTorchWrapper.podspec --use-libraries --allow-warnings
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Gradle Build
        run: ./gradlew build
